# -*- coding: utf-8 -*-
"""Statistics and Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWnX8uWkM3ONOxFcucZ6h-e2eBU7tlwm

# **Basic descriptive statistics**
"""

import statistics as st

data = [1,2,3,3]
data

mean= st.mean(data)
print('mean:' ,mean)
median = st.median(data)
print("median:" , median)
mode = st.mode(data)
print('mode:', mode)
stdev = st.stdev(data)
print('stdev:' , stdev)
variance = st.variance(data)
print('variance: ', variance)

"""# **Data visualizatoin**

**Line plot**
"""

import matplotlib.pyplot as plt
x_days = [1,2,46,7,8]

y_price1 = [3,4,5,6,7.7]
y_price2 = [1.1,2,3,6,7]

# define the chart elements
plt.title('Line plots',fontsize = 16)
plt.xlabel('days')
plt.ylabel('price$')

plt.plot(x_days,y_price1,label ='stock1')
plt.plot(x_days,y_price2,label= 'stock2')
plt.legend(loc=1, fontsize = 12)

plt.show()

"""**Bar chart**"""

import matplotlib.pyplot as plt

x_cities = ['NewYork', 'London', 'Dubai', 'New Delhi','Tokyo']
y_temp = [75,65,105,98,90]

plt.title('Temparature variation')
plt.xlabel('cities')
plt.ylabel('temparture')

plt.bar(x_cities,y_temp)

plt.show()

"""**Histogram**"""

import matplotlib.pyplot as plt

age = open('agedata.csv','r')

age = age.readlines()

print(age)
# interger list

age_list = []

for records in age:
  age_list.append(int(records))

print('after convert into list:',age_list)

bins = [10,20,30,40,50,60,70,80,90,100]


plt.title('age_group')
plt.xlabel('group')
plt.ylabel('no.0f age ppl')

plt.hist(age_list,bins,histtype='bar',rwidth = 0.9)

plt.show()

"""**Box plot**"""

import matplotlib.pyplot as plt

sales = open('salesdata.csv','r')

saledata = sales.readlines()

sale_list = []

for records in saledata:
  sale_list.append(int(records))

print(sale_list)
plt.title('box plot for the sale')

plt.boxplot(sale_list)

plt.show()

"""**Pie chart**"""

import matplotlib.pyplot as plt

f = open('agedata2.csv','r')
data = f.readlines()

city_list =[]
for records in data:
  age,city = records.split(sep=',')
  city_list.append(city)

print(city_list)

from collections import Counter

city_name = Counter(city_list)
print(city_name)
city_keys = list(city_name.keys())
city_values = list(city_name.values())


# pie chart
plt.pie(city_values,labels = city_keys ,autopct='%.2f%%')

plt.show()

"""**scatter **"""

import matplotlib.pyplot as plt

f = open('salesdata2.csv','r')
data = f.readlines()
print(data)
sales_list = []
cost_list = []

for records in data:
  sale, cost = records.split(sep=',')
  sales_list.append(int(sale))
  cost_list.append(int(cost))

print(sales_list)
print(cost_list)

plt.title('sales vs cost')
plt.xlabel('sales')
plt.ylabel('cost')

plt.scatter(sales_list, cost_list)

plt.show()

import matplotlib.pyplot as plt

f = open('salesdata2.csv','r')
data = f.readlines()
print(data)
sales_list = []
cost_list = []

for records in data:
  sale, cost = records.split(sep=',')
  sales_list.append(int(sale))
  cost_list.append(int(cost))

print(sales_list)
print(cost_list)


# scatter plot
plt.figure('sactter plot')
plt.title('sales vs cost')
plt.xlabel('sales')
plt.ylabel('cost')

plt.scatter(sales_list, cost_list)

plt.savefig('scatterplot.png')


# boxplot
plt.figure('boxplot')
plt.title('sales vs cost')

plt.boxplot(sales_list)

plt.savefig('boxplot.png')

plt.show()

"""**Two Box plot in one chart**"""

import matplotlib.pyplot as plt

f = open('salesdata2.csv','r')
data = f.readlines()
print(data)


###################################################
saletotal_list = []
sale_list = []
cost_list = []
for records in data:
  sale, cost = records.split(sep=',')
  sale_list.append(int(sale))
  cost_list.append(int(cost))

saletotal_list.append(sale_list)
saletotal_list.append(cost_list)

plt.figure('boxplot')
plt.title('sales vs cost')

plt.boxplot(saletotal_list)
plt.show()

"""**Sub plots**"""

import matplotlib.pyplot as plt

f = open('salesdata2.csv','r')
data = f.readlines()
print(data)


###################################################
saletotal_list = []
sale_list = []
cost_list = []
for records in data:
  sale, cost = records.split(sep=',')
  sale_list.append(int(sale))
  cost_list.append(int(cost))

saletotal_list.append(sale_list)
saletotal_list.append(cost_list)

## box plot
plt.subplot(2,2,1)
plt.title('sales vs cost')

plt.boxplot(saletotal_list)

#####################################
sales_list = []
cost_list = []

for records in data:
  sale, cost = records.split(sep=',')
  sales_list.append(int(sale))
  cost_list.append(int(cost))

print(sales_list)
print(cost_list)


# scatter plot
plt.subplot(2,2,2)
plt.title('sales vs cost')
plt.xlabel('sales')
plt.ylabel('cost')

plt.scatter(sales_list, cost_list)

plt.savefig('scatterplot.png')


# boxplot
plt.subplot(2,2,3)
plt.title('sales vs cost')

plt.boxplot(sales_list)

# prevent overlapping using tight_layout()
plt.tight_layout()

plt.savefig('boxplot.png')
plt.show()